version: '3'

services:
  django:
    build: .
    container_name: django
    command: ./docker-entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb
    env_file:
      - .env

  pgdb:
    image: postgres
    env_file: .env
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
